version: "2"
services:
  jpa-relation-test:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST_DIRECT: postgres
    depends_on:
      - postgres
  postgres:
    image: nexus.isb/postgres:11.9
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres