CREATE SCHEMA IF NOT EXISTS postgres;

CREATE SEQUENCE person_id_seq INCREMENT BY 50 MINVALUE 1 START 1;

CREATE TABLE person
(
    id BIGINT NOT NULL,
    PRIMARY KEY (id)
);


CREATE SEQUENCE phone_id_seq INCREMENT BY 50 MINVALUE 1 START 1;

CREATE TABLE phone
(
    id        BIGINT       NOT NULL,
    person_id BIGINT       NOT NULL,
    phone     VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE phone
    ADD CONSTRAINT FK_444F97DD217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

